name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2.1.5
    secrets: inherit
    with:
      provider: none
      working_directory: './examples/'  

 

